[package]
name = "video_effects"
version = "0.1.0"
edition = "2021"
authors = ["Yeauty <YeautyYE@gmail.com>"]
publish = false

[dependencies]
ez-ffmpeg = { path = "../../../ez-ffmpeg" , features = ["opengl"]}
