[package]
name = "processing_progress"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg-next = "7.1.0"
ffmpeg-sys-next = "7.1.0"
ez-ffmpeg = { path = "../../../ez-ffmpeg" , features = ["async"]}


[[bin]]
name = "processing_progress"
path = "main.rs"
